baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Rizky D. Novyantika"
  subtitle    = "All I know, I share with you"
  copyright   = "© 2018"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "rdnovyantika"
  fbName = "rizky.novyantika"
  githubName = "rizkynovyantika"
  linkedinName = "Rizky Dwi Novyantika"
  mediumName = "rizkynovyantika"

  logo = "logo.jpg"
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "EM"
  authorAvatar = "/img/avatar.jpg"
  authorLocation = "Yogyakarta, ID"
  authorWebsite = "https://rizkynovyantika.github.io"
  authorDescription = "I’m someone who very interested in the world of data, analysis, research to bring up something new that can be useful for others. Then engaging people, making ideas, things easier and simpler for them to understand through analysis, statistics and visualizing it."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "Portfolio"
  url = "https://github.com/rizkynovyantika"
  weight = 95